#!/bin/bash

VARIABLE=${1:-0}
sleep $VARIABLE

xmodmap -e "keycode 66 = Mode_switch"
xmodmap -e "keycode 31 = i I Up Up"
xmodmap -e "keycode 44 = j J Left Left"
xmodmap -e "keycode 45 = k K Down Down"
xmodmap -e "keycode 46 = l L Right Right"
xmodmap -e "keycode 30 = u U Prior Prior"
xmodmap -e "keycode 32 = o O Next Next"
xmodmap -e "keycode 43 = h H Home Home"
xmodmap -e "keycode 57 = n N End End"
xmodmap -e "keycode 65 = space space Menu Menu"
xmodmap -e "keycode 22 = BackSpace BackSpace Delete Delete"
